################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# monitor = name, resolution, position, scale
monitorv2 {
    output  = eDP-1
    mode    = 2880x1620@60
    position= 0x0
    scale   = 1.33
}

# work monitor
monitorv2 {
    output = HDMI-A-1
    mode = preferred
    position = auto-up
    scale = 1
}

xwayland {
    enabled = true
    force_zero_scaling = true
    use_nearest_neighbor = false
}

env = GDK_SCALE,2

# catch-all
monitor=, preferred, auto-up, 1