################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# monitor = name, resolution, position, scale
monitorv2 {
    output  = eDP-1
    mode    = 2880x1620
    position= 0x0
    scale   = 1.33
}

xwayland {
    enabled = true
    force_zero_scaling = true
    use_nearest_neighbor = false
}

env = GDK_SCALE,2

monitor=, preferred, auto-up, 1